<a href="https://colab.research.google.com/github/KateGavrish/first-task/blob/main/%D0%9F%D0%B5%D1%80%D0%B2%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Программист Миша владеет биткоинами, кошелек с которыми хранит на флешке с аппаратным шифрованием. Пароль от нее он записал на бумажке, которую потерял, а самостоятельно вспомнить нужную комбинацию ему не под силу. Единственное, что он знает про свой пароль, это что он является счастливым числом - то есть сумма первой половины числа совпадает со второй половиной числа, и он делится на 3, 13 и 73. Например, число 12344321 - счастливое. Известно, что пароль был шестизначным. Определите все возможные пароли, которые соответствуют условию.

In [7]:
def is_digit_happy(n):
  a = list(map(int, list(str(n))))  # Преобразуем число в строку, затем в список символов. Далее функцией map преобразуем каждый элемент списка в число
  if sum(a[:4]) == sum(a[4:]):      # Сравниваем суммы первой половины и второй
    return True
  return False


for i in range(100000, 1000000):
  if is_digit_happy(i) and i % 73 == 0 and i % 3 == 0 and i % 13 == 0:  # проверяем все условия
    print(i)

344487
350181
361569
390039
401427
780078

Ольга Бузова не остановилась на создании ресторана и Бузкоина и решила воплотить свои новую безумную идею - БузБанк. Дизайн пластиковых карт был давно разработан, осталось придумать красивые номера. Номер карты состоит из 10 цифр. Он уникален для конкретного банка и определенной платежной системы. Известно, что первые и последние четыре цифры 1986. Найти все номера карт БузБанка, которые при вышесказанных условиях делятся на 3 и 7

In [29]:
a1 = 1986001986  # Выбираем диапазон. Логично, что число имеет слудующую маску 1986--1986. Минимальное 1986001986 и максимальное 1986991986
a2 = 1986991986

for i in range(a1, a2 + 1):                                   # не забываем про то, что в питоне правая граница в range не включается, поэтому добавляем единичку
  if str(i)[-4:] == '1986' and i % 3 == 0 and i % 7 == 0:     # str(i)[-4:] разберем это выражение. Функция str(i) 
                                                              # преобразует число i в строку. Срез [-4:] берет последние 4 символа
    print(i)

1986151986
1986361986
1986571986
1986781986
1986991986

В 73-й серии сериала «Теория большого взрыва» Шелдон Купер заметил, что число 73 обладает тремя нетривиальными свойствами, которые делают его «самым замечательным числом».
73 — это 21-ое простое число. Его зеркальное отражение 37 является 12-ым, чье отражение 21 является результатом умножения, не упадите, 7 и 3.
Так как Шелдон любит точность и аккуратность, давай найдём все числа в диапазоне [45387634, 375630355], которые делятся на 3, 7 и 73, заканчиваются на 1234 и начинаются на 1

In [37]:
def check(n):
  if (n % 3 == 0 and n % 7 == 0 and n % 73 == 0         # str(i)[-4:] разберем это выражение. Функция str(i) преобразует число i в строку.
      and str(n)[-4:] == '1234' and str(n)[0] == '1'):  # Срез [-4:] берет последние 4 символа
    return True
  return False

for i in range(45387634, 375630356, 2): # рассмотрим генератор range(start, end, step) начало, конец (не включая) и шаг. 
  if check(i):                          # Тут мы знаем, что число четное, так как последняя цифра 4
    print(i)

102861234
118191234
133521234
148851234
164181234
179511234
194841234